<NavtoSignUpScreen>:
    BoxLayout:
        Image:
            source: 'image\login.jpg'  # Replace 'path_to_image_home.png' with the path to your home image
            allow_stretch: True
            keep_ratio: False
    MDGridLayout:
        cols:1
        rows:1
        spacing:"20dp"
        padding: "70dp"
        size_hint_y: None
        height: root.height/1.7
        SCardScreen:
